### ISSUE TITLE
Fails on narrow terminal sizes

### ISSUE THREAD

**Issue by abitrolly** [jarekj9/scapy_dhcp_tester#1]
`scapy_dhcp_tester` fails to start if terminal is not a standard size, but smaller. This is easily repeatable.
```
✗ python dhcpTester.py
Traceback (most recent call last):
  File "dhcpTester.py", line 437, in <module>
    main()
  File "dhcpTester.py", line 434, in main
    menuObj = Menu(['DHCP Starve', 'DHCP Spoof', 'DHCP Discover', 'Sniff for DHCP Packets'])
  File "dhcpTester.py", line 201, in __init__
    curses.wrapper(self.draw_menu)
  File "/usr/lib64/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "dhcpTester.py", line 246, in draw_menu
    self.stdscr.addstr(self.start_y+y, self.start_x_title-35, line)
_curses.error: addwstr() returned ERR
```

**Comment by jarekj9** [comment]
Thank you :) it should be fixed now, though minimum height/width will be 20/65
